site_name: Nemesis Documentation
site_url: https://specterops.github.io/Nemesis/
repo_url: https://github.com/SpecterOps/Nemesis
repo_name: SpecterOps/Nemesis
edit_uri: edit/main/docs/

plugins:
  - search


exclude_docs: |
  /requirements.txt

nav:
  - Nemesis: index.md
  - Quickstart: quickstart.md
  - overview.md

  - Installation:
    - Setup: setup.md
    - Requirements: requirements.md
    - Unsupported Platforms:
        - Docker Desktop: requirements_docker_desktop.md
        - Minikube: requirements_minikube.md
    - Quickstart Chart: quickstart_chart.md
    - Nemesis Chart: nemesis_chart.md

  - Usage:
    - usage_guide.md
    - access_nemesis.md
    - submit_to_nemesis.md
    - kubernetes.md
    - troubleshooting.md

  - Services:
    - postgres.md
    - rabbitmq.md
    - elasticsearch-kibana.md
    - hasura.md

  - Developer:
    - requirements_developer.md
    - development.md
    - remote_debugging.md
    - new_connector.md
    - new_seatbelt_datatype_ingestion.md
    - new_service.md
    - new_odr_datatype.md

  - Operational Data References:
    - odr/README.md
    - References:
      - odr/references/authentication_data.md
      - odr/references/cookie.md
      - odr/references/file_data.md
      - odr/references/file_information.md
      - odr/references/network_connection.md
      - odr/references/path_list.md
      - odr/references/raw_data.md
      - Host Data:
        - odr/references/host_data/named_pipe.md
        - odr/references/host_data/process.md
        - odr/references/host_data/registry_value.md
        - odr/references/host_data/service.md

theme:
  name: material
  locale: en
  logo: images/logo.png
  favicon: images/logo.png

  features:
    - navigation.sections

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: nemesis-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: nemesis-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/colors.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true