site_name: Nemesis Documentation
site_url: https://specterops.github.io/Nemesis/
repo_url: https://github.com/SpecterOps/Nemesis
repo_name: SpecterOps/Nemesis
edit_uri: edit/main/docs/

exclude_docs: |
  /requirements.txt

theme:
  name: material
  locale: en
  logo: images/logo.png
  favicon: images/logo.png

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: nemesis-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: nemesis-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/colors.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
