site_name: Nemesis Documentation
site_url: https://specterops.github.io/Nemesis/
repo_url: https://github.com/SpecterOps/Nemesis
repo_name: SpecterOps/Nemesis
edit_uri: edit/main/docs/

plugins:
  - search

exclude_docs: |
  /requirements.txt

nav:
  - Nemesis: index.md
  - Quickstart: quickstart.md

  - Usage:
    - usage_guide.md
    - enrichment_configuration.md
    - alerting.md
    - cli.md
    - agents.md
    - chatbot.md
    - troubleshooting.md
    - yara.md
    - Chromium Analysis: chromium.md
    - DPAPI Analysis: dpapi.md
    - Container Processing: containers.md
    - reporting.md
    - Performance Tuning: performance.md

  - Services:
    - hasura.md
    - jupyter.md
    - housekeeping.md

  - Developer:
    - Project Overview: overview.md
    - Adding File Enrichment Modules: file_enrichment_modules.md
    - Operational Data Reference: odr.md
    - Docker Compose Documentation: docker_compose.md
    - Nemesis API: api.md

theme:
  name: material
  locale: en
  logo: images/logo.png
  favicon: images/logo.png

  features:
    - navigation.sections
    - content.code.copy

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: nemesis-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: nemesis-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/colors.css

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true