operation:
  secretName: operation
  slackWebhook: "https://hooks.slack.com/services/some/random/text"

basicAuth:
  secretName: basic-auth
  username: "nemesis"
  # Add a value to the password field to set a static password
  password:

aws:
  secretName: aws-creds
  accessKeyId: not-applicable
  secretKey: not-applicable

rabbitmq:
  secretName: rabbitmq-creds
  adminUser: "nemesis"
  adminPassword: "password"
  connectionUri: "amqp://nemesis:password@nemesis-rabbitmq-svc:5672/"
  erlangCookie: "default-cookie"

grafana:
  secretName: grafana-creds
  username: "nemesis"
  # Add a value to the password field to set a static password
  password:

minio:
  secretName: minio-creds
  rootUser: nemesis
  # Add a value to the rootPassword field to set a static password
  rootPassword:

elasticsearch:
  secretName: elasticsearch-creds
  user: "nemesis"
  # NOTE: if you're use persist "production" storage, this needs to be set to a static value
  #   ahead of time for services to play nicely together
  password: "Qwerty12345"

dashboard:
  secretName: dashboard-creds
  username: "nemesis"
  # not actually used anymore as auth is disabled for the dashboard
  password:

postgres:
  secretName: postgres-creds
  username: "nemesis"
  pgadminEmail: "nemesis@nemesis.com"
  # Add a value to the password field to set a static password
  pgadminPassword:

jupyter:
  secretName: jupyter-creds
  # Add a value to the token field to set a static password
  token:

tls:
  secretName: nemesis-cert
  enable: true