apiVersion: v1
kind: ConfigMap
metadata:
  name: operation-config
data:
  slack-alert-channel: {{ default "" .Values.operation.slackChannel | quote }}
  disable-slack-alerting: {{ default "true" .Values.operation.disableSlackAlerting | quote }}
  log-level: {{ default "INFO" .Values.operation.logLevel | quote }}
  assessment-id: {{ .Values.operation.assessmentId | quote }}
  storage_provider: {{ default "minio" .Values.operation.storageProvider | quote }}
  nemesis-http-server: {{ .Values.operation.nemesisHttpServer | quote }}
  environment: {{ default "testing" .Values.operation.environment | quote }}
  data-expiration-days: {{ default "100" .Values.operation.dataExpirationDays | quote }}