apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: schedulerconfig
spec:
  # workflow:
  #   maxConcurrentWorkflowInvocations: 1
  #   maxConcurrentActivityInvocations: 1
  httpPipeline:
    handlers:
    - name: maximum-request-size
      type: middleware.http.requestsize
      properties:
        maxBodySize: "300MB"