rules:
  - name: sha256crypt Hash
    pattern: '(\$5\$(?:rounds=\d+\$)?[\./A-Za-z0-9]{1,16}\$(?:(?:[\./A-Za-z0-9]{43})))'
    references:
      - https://akkadia.org/drepper/SHA-crypt.txt
      - https://hashcat.net/wiki/doku.php?id=example_hashes
    examples:
      - '$5$rounds=5000$GX7BopJZJxPc/KEK$le16UF8I2Anb.rOrn22AUPWvzUETDGefUmAV8AZkGcD'
      - '$5$B7RCoZun804NXFH3$PltCS6kymC/bJTQ21oQOMCLlItYP9uXvEaCV89jl5iB'
      - '$5$JzPB.C/yL0uBMMIK$/2Jr.LeQUg0Sgbm8UhF01d1X643/YHdmRzwlVmt3ut3'
      - '$5$rounds=80000$wnsT7Yr92oJoP28r$cKhJImk5mfuSKV9b3mumNzlbstFUplKtQXXMo4G6Ep5'
      - '$5$rounds=12345$q3hvJE5mn5jKRsW.$BbbYTFiaImz9rTy03GGi.Jf9YY5bmxN0LU3p3uI1iUB'


  - name: sha512crypt Hash
    pattern: '(\$6\$(?:rounds=\d+\$)?[\./A-Za-z0-9]{1,16}\$(?:(?:[\./A-Za-z0-9]{43})))'
    references:
      - https://akkadia.org/drepper/SHA-crypt.txt
      - https://hashcat.net/wiki/doku.php?id=example_hashes
    examples:
      - '$6$52450745$k5ka2p8bFuSmoVT1tzOyyuaREkkKBcCNqoDKzYiJL9RaE8yMnPgh2XzzF0NDrUhgrcLwg78xs1w5pJiypEdFX/'
      - '$6$Blzt0pLMHZqPNTwR$jR4F0zo6hXipl/0Xs8do1YWRpr47mGcH49l.NCsJ6hH0VQdORfUP1K1HYar1a5XgH1/JFyTGnyrTPmKJBIoLx.'


  # - name: md5 Hash
  #   pattern: '(?:(?:.*[^0-9a-zA-Z]+)|(?:\A|\r|\n|\r\n))([0-9a-fA-F]{32})(?:(?:[^0-9a-zA-Z]+.*)|(?:\z|\r|\n|\r\n))'
  #   references:
  #   - https://en.wikipedia.org/wiki/MD5
  #   - https://hashcat.net/wiki/doku.php?id=example_hashes
  #   examples:
  #   - c123bdb6574e817ac0a5f8b2e097b986
  #   - "This is a matching hash:c3b4e0d9409362db47eaf45ea025befb"
  #   #- "This is NOT a matching hash:c3b4e0d9409362db47eaf45ea025befba"


  # - name: sha1 Hash
  #   pattern: '(?:(?:.*[^0-9a-zA-Z]+)|(?:\A|\r|\n|\r\n))([0-9a-fA-F]{40})(?:(?:[^0-9a-zA-Z]+.*)|(?:\z|\r|\n|\r\n))'
  #   references:
  #   - https://en.wikipedia.org/wiki/SHA-1
  #   - https://hashcat.net/wiki/doku.php?id=example_hashes
  #   examples:
  #   - c3ebd40a7429b6bfee7ee0be896698709fc3cc58
  #   - "This is a matching hash:46d66eccea3d78f91b363940c0e2148d6e2c69cc"
  #   #- "This is NOT a matching hash:46d66eccea3d78f91b363940c0e2148d6e2c69ccd"


  # - name: sha256 Hash
  #   pattern: '(?:(?:.*[^0-9a-zA-Z]+)|(?:\A|\r|\n|\r\n))([0-9a-fA-F]{64})(?:(?:[^0-9a-zA-Z]+.*)|(?:\z|\r|\n|\r\n))'
  #   references:
  #   - https://en.wikipedia.org/wiki/SHA-2
  #   - https://hashcat.net/wiki/doku.php?id=example_hashes
  #   examples:
  #   - 503cae96893c71dafb3b2676f532b4e338615b1970c1fa2a6289d690565815a9
  #   - "Hash:fa6bfe5050c224a5b156192a2532c7bacc66984ed18ae7eb78dcce0aa889b553"


  # - name: sha512 Hash
  #   pattern: '(?:(?:.*[^0-9a-zA-Z]+)|(?:\A|\r|\n|\r\n))([0-9a-fA-F]{128})(?:(?:[^0-9a-zA-Z]+.*)|(?:\z|\r|\n|\r\n))'
  #   references:
  #   - https://en.wikipedia.org/wiki/SHA-2
  #   - https://hashcat.net/wiki/doku.php?id=example_hashes
  #   examples:
  #   - 89e2c4ee9acf9b8a75b3996cc1888c7e7b12abfe5d6274ed833f28c0e741f3da179a4e08382e8a933304bb70cbc56eb91ad574ac10ef74387d7a1e0f914b9e49
  #   - "This matches:28404ec2e13d737421d1fc7b0e9a714bef205a94909f3cc9364cb6071d41470c1716c9624197b8035e07c0cf1541efada2fce1b3e2a6be5f69a5586c6c1d66f3"


  # TODO: should the MSSQL hashes also include lower case?
  - name: MSSQL 2000 Hash
    pattern: '(?:(?:.*[^0-9a-zA-Z]+)|(?:\A|\r|\n|\r\n))(0x0100[0-9aA-Z]{88})(?:(?:[^0-9a-zA-Z]+.*)|(?:\z|\r|\n|\r\n))'
    references:
      - https://passlib.readthedocs.io/en/stable/lib/passlib.hash.mssql2000.html#format-algorithm
      - https://hashcat.net/wiki/doku.php?id=example_hashes
    examples:
      - "0x0100B8774E298FB5A76E6F6B2F81D774C0D259013EEBA4DB055A2D60D9196C5B39E8CB7C0743D440B839FC4DD213"
      - "This matches:0x0100E27C4F095B63A0E0F6C2F70E26FD5B19814EF48178AD0BF4BCB0E4E3413E4F840DF235E27334F9864760858B"
      #- "This DOESN'T match:0x010005A09412D92CE07A0EA0F23D59847CF6569115DB3DD9F26B389CF22BDE0BE007C3D3145146D0ABC78723B0899"


  - name: MSSQL 2012/2014 Hash
    pattern: '(?:(?:.*[^0-9a-zA-Z]+)|(?:\A|\r|\n|\r\n))(0x0200[0-9aA-Z]{136})(?:(?:[^0-9a-zA-Z]+.*)|(?:\z|\r|\n|\r\n))'
    references:
      - https://hashcat.net/forum/thread-1474.html
      - https://hashcat.net/wiki/doku.php?id=example_hashes
    examples:
      - "0x0200F733058A07892C5CACE899768F89965F6BD1DED7955FE89E1C9A10E27849B0B213B5CE92CC9347ECCB34C3EFADAF2FD99BFFECD8D9150DD6AACB5D409A9D2652A4E0AF16"
      - "This matches:0x0200881E2999DD8E3583695F405696257B99559953705A34D774C15AC1D42699BB77BC56DB5F657751335C1B350890E643790553B60329CAE7A2E7D3C04CF8856C4DB0058723"


  - name: CISCO-IOS Type 8 Hash
    pattern: '(?:(?:.*[^0-9a-zA-Z]+)|(?:\A|\r|\n|\r\n))(\$8\$[0-9a-zA-Z\./]{14}\$[0-9a-zA-Z\./]{43})(?:(?:[^0-9a-zA-Z]+.*)|(?:\z|\r|\n|\r\n))'
    references:
      - https://foss.heptapod.net/python-libs/passlib/-/issues/87
      - https://hashcat.net/wiki/doku.php?id=example_hashes
    examples:
      - "$8$TnGX/fE4KGHOVU$pEhnEvxrvaynpi8j4f.EMHr6M.FzU8xnZnBr/tJdFWk"


  - name: CISCO-IOS Type 9 Hash
    pattern: '(?:(?:.*[^0-9a-zA-Z]+)|(?:\A|\r|\n|\r\n))(\$9\$[0-9a-zA-Z\./]{14}\$[0-9a-zA-Z\./]{43})(?:(?:[^0-9a-zA-Z]+.*)|(?:\z|\r|\n|\r\n))'
    references:
      - https://foss.heptapod.net/python-libs/passlib/-/issues/87
      - https://hashcat.net/wiki/doku.php?id=example_hashes
    examples:
      - "This matches:$9$2MJBozw/9R3UsU$2lFhcKvpghcyw8deP25GOfyZaagyUOGBymkryvOdfo6"
