tls:
  certificates:
    - certFile: "/certs/server.crt"
      keyFile: "/certs/server.key"
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/server.crt"
        keyFile: "/certs/server.key"