apiVersion: v2
name: nemesis
description: Nemesis is an offensive data enrichment pipeline and operator support system.
type: application
version: 1.0.0
appVersion: "0.1.0a"
icon: https://github.com/SpecterOps/Nemesis/raw/main/img/nemesis_white.png

dependencies:
- name: minio
  version: 12.13.1
  repository: https://charts.bitnami.com/bitnami